export interface LLMMessage {
  role: 'system' | 'user' | 'assistant';
  content: string;
}

export interface LLMResponse {
  text: string;
  usage?: {
    promptTokens: number;
    completionTokens: number;
    totalTokens: number;
  };
}

export interface LLMProvider {
  name: string;
  generateContent(messages: LLMMessage[], options?: any): Promise<LLMResponse>;
}

export class MockLLMProvider implements LLMProvider {
  name = 'MockLLM';

  async generateContent(messages: LLMMessage[], options?: any): Promise<LLMResponse> {
    console.log('[MockLLMProvider] Received messages:', messages);
    
    // Simulate network delay
    await new Promise(resolve => setTimeout(resolve, 800));

    return {
      text: JSON.stringify({
        action: 'mock_action',
        reasoning: 'Generated by mock provider based on system prompt constraints.',
        confidence: 0.95
      }),
      usage: {
        promptTokens: 100,
        completionTokens: 25,
        totalTokens: 125
      }
    };
  }
}

// In a real scenario, you would implement GoogleGeminiProvider or OpenAIProvider here.
export class GeminiLLMProvider implements LLMProvider {
  name = 'Gemini';

  async generateContent(messages: LLMMessage[], options?: any): Promise<LLMResponse> {
    const apiKey = process.env.LLM_API_KEY;
    if (!apiKey) {
      console.warn('LLM_API_KEY is missing. Falling back to MockLLMProvider.');
      return new MockLLMProvider().generateContent(messages, options);
    }
    
    // Placeholder for actual Gemini API call
    console.log('[GeminiLLMProvider] Using real LLM key for generation');
    
    // Mocking real response for now to keep the project standalone without billing
    return {
      text: JSON.stringify({
        action: 'extracted_data',
        data: 'Simulated real data from Gemini'
      })
    };
  }
}

export function getDefaultLLMProvider(): LLMProvider {
  if (process.env.NODE_ENV === 'development' && !process.env.LLM_API_KEY) {
    return new MockLLMProvider();
  }
  return new GeminiLLMProvider();
}
