export interface LLMMessage {
  role: 'system' | 'user' | 'assistant';
  content: string;
}

export interface LLMResponse {
  text: string;
  usage?: {
    promptTokens: number;
    completionTokens: number;
    totalTokens: number;
  };
}

export interface LLMProvider {
  name: string;
  generateContent(messages: LLMMessage[], options?: any): Promise<LLMResponse>;
}

export class MockLLMProvider implements LLMProvider {
  name = 'MockLLM';

  async generateContent(messages: LLMMessage[], options?: any): Promise<LLMResponse> {
    console.log('[MockLLMProvider] Received messages:', messages);
    
    // Simulate network delay
    await new Promise(resolve => setTimeout(resolve, 800));

    return {
      text: JSON.stringify({
        action: 'mock_action',
        reasoning: 'Generated by mock provider based on system prompt constraints.',
        confidence: 0.95
      }),
      usage: {
        promptTokens: 100,
        completionTokens: 25,
        totalTokens: 125
      }
    };
  }
}

export class GrokLLMProvider implements LLMProvider {
  name = 'Grok';

  async generateContent(messages: LLMMessage[], options?: any): Promise<LLMResponse> {
    const apiKey = process.env.GROK_API_KEY;
    if (!apiKey) {
      console.warn('GROK_API_KEY is missing. Falling back to MockLLMProvider.');
      return new MockLLMProvider().generateContent(messages, options);
    }
    
    console.log('[GrokLLMProvider] Calling x.ai API...');
    
    const response = await fetch('https://api.x.ai/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${apiKey}`
      },
      body: JSON.stringify({
        model: 'grok-beta', // or 'grok-2-latest'
        messages: messages,
        temperature: options?.temperature || 0.1,
        response_format: options?.response_format || { type: 'text' }
      })
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('[GrokLLMProvider] API Error:', errorText);
      throw new Error(`Grok API Error: ${response.status} - ${errorText}`);
    }

    const data = await response.json();
    const content = data.choices[0].message.content;

    return {
      text: content,
      usage: {
        promptTokens: data.usage?.prompt_tokens || 0,
        completionTokens: data.usage?.completion_tokens || 0,
        totalTokens: data.usage?.total_tokens || 0
      }
    };
  }
}

export function getDefaultLLMProvider(): LLMProvider {
  if (process.env.GROK_API_KEY) {
    return new GrokLLMProvider();
  }
  return new MockLLMProvider();
}
