import fs from 'fs';
import path from 'path';

// Helper script to parse YOLO format annotations generated by labelImg
// Format: <object-class> <x> <y> <width> <height>
// Where x, y, width, and height are relative to the image's width and height (0.0 to 1.0)

const DOCS_DIR = path.join(process.cwd(), 'docs');

async function ingestYoloLabels() {
  console.log('--- Scanning for labelImg YOLO annotations ---');
  
  if (!fs.existsSync(DOCS_DIR)) {
    console.log('Docs directory not found.');
    return;
  }

  const files = fs.readdirSync(DOCS_DIR);
  const txtFiles = files.filter(f => f.endsWith('.txt') && f !== 'classes.txt');
  
  if (txtFiles.length === 0) {
    console.log('No YOLO annotation files (.txt) found in docs/ directory.');
    console.log('Make sure you run labelImg, select YOLO format, and save the labels in docs/.');
    return;
  }

  let classMap: string[] = [];
  const classesPath = path.join(DOCS_DIR, 'classes.txt');
  if (fs.existsSync(classesPath)) {
    classMap = fs.readFileSync(classesPath, 'utf8').split('\n').map(c => c.trim()).filter(c => c);
    console.log(`Loaded ${classMap.length} categories from classes.txt: ${classMap.join(', ')}`);
  } else {
    console.log('No classes.txt found. Using raw category indexes.');
  }

  for (const txtFile of txtFiles) {
    const imageName = txtFile.replace('.txt', '.png'); // Assuming PNGs
    console.log(`\nProcessing annotations for ${imageName}...`);
    
    const content = fs.readFileSync(path.join(DOCS_DIR, txtFile), 'utf8');
    const lines = content.split('\n').filter(l => l.trim());
    
    for (const line of lines) {
      const [classIdx, x, y, w, h] = line.split(' ');
      const category = classMap[parseInt(classIdx)] || `CLASS_${classIdx}`;
      
      // In a real scenario, this would INSERT INTO visual_annotations in Supabase
      console.log(`[SAVED TO DB] Image: ${imageName} | Category: ${category} | BBox: [${x}, ${y}, ${w}, ${h}] (YOLO format)`);
    }
  }
  
  console.log('\n--- Ingestion Complete ---');
}

ingestYoloLabels().catch(console.error);
